language: go
go: 1.8.1
sudo: false

services:
  - docker

before_install:
  - docker pull antihax/mock-esi
  - docker run -d -p 127.0.0.1:8080:8080 antihax/mock-esi
  - docker ps -a

script:
  - bash build_esi.sh